# Generated by Django 4.2.4 on 2023-09-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_matches', to='main.matches', verbose_name='кто оставил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favourites', to=settings.AUTH_USER_MODEL, verbose_name='кого')),
            ],
            options={
                'verbose_name': 'избранные',
                'verbose_name_plural': 'избранные',
                'ordering': ('-id',),
            },
        ),
    ]
